services:
  server:
    image: docker.gitea.com/gitea:1.23.7
    container_name: gitea
    environment:
      # Fallback to 1000 if uid/gid is not defined.
      # Note that it's not -1000 that we fall back to, i.e. ${VAR:-hello}
      # falls back to hello, NOT -hello
      - USER_UID=${PODMAN_UID:-1000}
      - USER_GID=${PODMAN_GID:-1000}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:17
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${GITEA_POSTGRES_PASSWORD:?Postgres password must be set}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - gitea-postgres-data:/var/lib/postgresql/data

networks:
  gitea:
    external: false

volumes:
  gitea-data:
  gitea-postgres-data:
